---
abstract: 'HTML::Table plugin for Data::Tabulate'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102160'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Tabulate-Plugin-HTMLTable
requires:
  Data::Tabulate: 0.06
  HTML::Table: 2.08
  Test::CheckManifest: 1.22
  Test::More: 0
version: 0.03
