---
name: Data-Tabulate-Plugin-HTMLTable
version: 0.01
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: HTML::Table plugin for Data::Tabulate
license: perl
build_requires:
  Data::Tabulate: 0.02
  HTML::Table: 2
  Test::CheckManifest: 1
  Test::More: 0
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Data::Tabulate::Plugin::HTMLTable:
    file: lib/Data/Tabulate/Plugin/HTMLTable.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
