---
name: Data-Tabulate-Plugin-HTMLTable
version: 0.02
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: HTML::Table plugin for Data::Tabulate
license: perl
requires:
  Data::Tabulate: 0.04
  HTML::Table: 2
build_requires:
  Data::Tabulate: 0.04
  HTML::Table: 2
  Test::CheckManifest: 1
  Test::More: 0
provides:
  Data::Tabulate::Plugin::HTMLTable:
    file: lib/Data/Tabulate/Plugin/HTMLTable.pm
    version: 0.02
generated_by: Module::Build version 0.26
